version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14.17 # 选择你需要的 Docker 镜像
    steps:
      - checkout # 拉取代码
      - run:
          name: Pull Docker image
          command: docker pull schrodingernft/interface:latest # 拉取 Docker 镜像
      - run:
          name: Deploy to target location
          command: |
            # 在这里执行部署到对应位置的命令，例如：
            docker run -d -p 8080:80 schrodingernft/interface:latest

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy
